project:
  type: website
  output-dir: docs

website:
  title: "personal_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text : About me
        menu: 
          - resume.qmd
          - graphic_resume.qmd
  reader-mode: true
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

