project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text : About me
        menu: 
          - href: resume.qmd
            text: "Resume" 
          - href: graphic_resume.qmd
            text: "Visual Resume"
  reader-mode: true
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

